from pathlib import Path
import stat

from dos_machines.application.config_renderer import ConfigRenderer
from dos_machines.application.engine_registry import EngineRegistry
from dos_machines.application.import_service import ImportService
from dos_machines.application.profile_service import ProfileService
from dos_machines.application.settings_service import SettingsService


def _fake_binary(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "#!/bin/sh\n"
        "if [ \"$1\" = \"--list-glshaders\" ]; then\n"
        "  echo crt-auto\n"
        "  echo sharp\n"
        "  exit 0\n"
        "fi\n"
        "echo 'dosbox staging 0.81.0'\n",
        encoding="utf-8",
    )
    path.chmod(path.stat().st_mode | stat.S_IEXEC)
    return path


def _import_service(tmp_path: Path) -> tuple[ImportService, ProfileService, Path]:
    settings_service = SettingsService(config_root=tmp_path / "config")
    settings_service.load()
    engine_registry = EngineRegistry(settings_service.app_paths)
    profile_service = ProfileService(settings_service.app_paths, engine_registry, ConfigRenderer())
    binary = _fake_binary(tmp_path / "bin" / "dosbox")
    return ImportService(engine_registry, profile_service), profile_service, binary


def test_analyse_general_config_preserves_autoexec_and_unknown_sections(tmp_path: Path, monkeypatch) -> None:
    service, _, binary = _import_service(tmp_path)
    monkeypatch.setattr(
        "dos_machines.application.import_service.shutil.which",
        lambda name: str(binary) if name in {"dosbox", "dosbox-staging"} else None,
    )
    config_path = tmp_path / "keen4" / "dosbox.conf"
    config_path.parent.mkdir(parents=True)
    config_path.write_text(
        "[sdl]\n"
        "fullscreen = true\n"
        "\n"
        "[custom]\n"
        "foo = bar\n"
        "\n"
        "[autoexec]\n"
        "mount c \".\"\n"
        "c:\n"
        "cd \\\n"
        "KEEN4E.EXE\n",
        encoding="utf-8",
    )

    analysis = service.analyse_config(config_path)

    assert analysis.is_managed_config is False
    assert analysis.game_dir == config_path.parent
    assert analysis.executable == "KEEN4E.EXE"
    assert analysis.autoexec_text.endswith("KEEN4E.EXE")
    assert analysis.option_states["sdl"]["fullscreen"].value == "true"
    assert analysis.option_states["sdl"]["fullscreen"].checked is True
    assert analysis.raw_overrides == {"custom": {"foo": "bar"}}


def test_import_managed_config_uses_parent_game_dir_and_keeps_provenance(tmp_path: Path, monkeypatch) -> None:
    service, profile_service, binary = _import_service(tmp_path)
    monkeypatch.setattr(
        "dos_machines.application.import_service.shutil.which",
        lambda name: str(binary) if name in {"dosbox", "dosbox-staging"} else None,
    )
    config_path = tmp_path / "games" / "doom" / ".dosmachines" / "dosbox.conf"
    config_path.parent.mkdir(parents=True)
    config_path.write_text(
        "# Generated by DOS Machines\n"
        "[sdl]\n"
        "fullscreen = false\n"
        "\n"
        "[autoexec]\n"
        "mount c \"..\"\n"
        "c:\n"
        "DOOM.EXE\n",
        encoding="utf-8",
    )

    profile = service.import_config(config_path, tmp_path / "workspace")
    reloaded = profile_service.load(profile.game.game_dir / ".dosmachines" / "profile.json")

    assert profile.game.game_dir == tmp_path / "games" / "doom"
    assert profile.identity.title == "doom"
    assert profile.autoexec_text == ""
    assert reloaded.provenance.import_source_path == config_path.resolve()
    assert reloaded.game.executable == "DOOM.EXE"


def test_analyse_config_reports_unknown_and_invalid_settings(tmp_path: Path, monkeypatch) -> None:
    service, _, binary = _import_service(tmp_path)
    monkeypatch.setattr(
        "dos_machines.application.import_service.shutil.which",
        lambda name: str(binary) if name in {"dosbox", "dosbox-staging"} else None,
    )
    config_path = tmp_path / "weird" / "dosbox.conf"
    config_path.parent.mkdir(parents=True)
    config_path.write_text(
        "[sdl]\n"
        "fullscreen = maybe\n"
        "mystery = true\n"
        "\n"
        "[alien]\n"
        "foo = bar\n",
        encoding="utf-8",
    )

    analysis = service.analyse_config(config_path)

    assert analysis.has_issues is True
    assert any(issue.option_name == "fullscreen" for issue in analysis.issues)
    assert any(issue.option_name == "mystery" for issue in analysis.issues)
    assert any(issue.section_name == "alien" and issue.option_name is None for issue in analysis.issues)
