from __future__ import annotations

from dos_machines.domain.models import EngineSchema, MachineProfile


class ConfigRenderer:
    """Render a managed DOSBox config from the stored profile."""

    def render(self, profile: MachineProfile, schema: EngineSchema) -> str:
        lines = [
            "# Generated by DOS Machines",
            f"# Machine: {profile.identity.title}",
            "",
        ]
        for section in schema.sections:
            if section.name == "autoexec":
                continue
            lines.append(f"[{section.name}]")
            for option in section.options:
                state = profile.option_states.get(section.name, {}).get(option.name)
                value = state.value if state is not None else option.default_value
                lines.append(f"{option.name} = {value}")
            lines.append("")

        lines.extend(
            [
                "[autoexec]",
                f"mount c \"{profile.game.game_dir}\"",
                "c:",
                self._render_cd(profile),
            ]
        )
        if profile.game.executable:
            lines.append(profile.game.executable)
        lines.append("")

        for section in sorted(profile.raw_overrides):
            if section not in {schema_section.name for schema_section in schema.sections}:
                lines.append(f"[{section}]")
            for key, value in sorted(profile.raw_overrides[section].items()):
                lines.append(f"{key}={value}")
            lines.append("")

        return "\n".join(lines).strip() + "\n"

    def _render_cd(self, profile: MachineProfile) -> str:
        if profile.game.working_dir == profile.game.game_dir:
            return "cd \\"
        try:
            relative = profile.game.working_dir.relative_to(profile.game.game_dir)
        except ValueError:
            return "cd \\"
        relative_text = str(relative).replace("/", "\\")
        return f"cd \"\\{relative_text}\""
