from __future__ import annotations

from dos_machines.domain.models import MachineProfile


class ConfigRenderer:
    """Render a managed DOSBox config from the stored profile."""

    def render(self, profile: MachineProfile) -> str:
        sections: dict[str, dict[str, object]] = {}
        for section, values in profile.machine_overrides.items():
            sections.setdefault(section, {}).update(values)

        lines = [
            "# Generated by DOS Machines",
            f"# Machine: {profile.identity.title}",
            "",
        ]
        for section in sorted(sections):
            lines.append(f"[{section}]")
            for key, value in sorted(sections[section].items()):
                lines.append(f"{key}={value}")
            lines.append("")

        lines.extend(
            [
                "[autoexec]",
                f"mount c \"{profile.game.game_dir}\"",
                "c:",
                self._render_cd(profile),
                profile.game.executable,
                "",
            ]
        )

        for section in sorted(profile.raw_overrides):
            if section not in sections:
                lines.append(f"[{section}]")
            for key, value in sorted(profile.raw_overrides[section].items()):
                if section in sections and key in sections[section]:
                    continue
                lines.append(f"{key}={value}")
            lines.append("")

        return "\n".join(lines).strip() + "\n"

    def _render_cd(self, profile: MachineProfile) -> str:
        if profile.game.working_dir == profile.game.game_dir:
            return "cd \\"
        try:
            relative = profile.game.working_dir.relative_to(profile.game.game_dir)
        except ValueError:
            return "cd \\"
        relative_text = str(relative).replace("/", "\\")
        return f"cd \"\\{relative_text}\""
