from __future__ import annotations

from pathlib import Path

from dos_machines.application.engine_support import detect_engine_family_from_name, ENGINE_FAMILY_DOSBOX_X
from dos_machines.domain.models import EngineSchema, GameTargets, MachineProfile


class ConfigRenderer:
    """Render a managed DOSBox config from the stored profile."""

    def render(self, profile: MachineProfile, schema: EngineSchema) -> str:
        lines = [
            "# Generated by DOS Machines",
            f"# Machine: {profile.identity.title}",
            "",
        ]
        for section in schema.sections:
            lines.append(f"[{section.name}]")
            if section.name == "autoexec":
                lines.extend(self.render_autoexec_text(profile).splitlines())
                lines.append("")
                continue
            for option in section.options:
                for comment_line in option.comment_lines:
                    lines.append(comment_line if comment_line.startswith("#") else f"#{comment_line}")
                state = profile.option_states.get(section.name, {}).get(option.name)
                value = state.value if state is not None else option.default_value
                lines.append(f"{option.name} = {value}")
                lines.append("")
            if section.options:
                if lines[-1] == "":
                    pass
            lines.append("")

        for section in sorted(profile.raw_overrides):
            if section not in {schema_section.name for schema_section in schema.sections}:
                lines.append(f"[{section}]")
            for key, value in sorted(profile.raw_overrides[section].items()):
                lines.append(f"{key}={value}")
            lines.append("")

        return "\n".join(lines).strip() + "\n"

    def _render_cd(self, profile: MachineProfile) -> str:
        return self._render_cd_from_game(profile.game)

    def _render_cd_from_game(self, game: GameTargets) -> str:
        if game.working_dir == game.game_dir:
            return "cd \\"
        try:
            relative = game.working_dir.relative_to(game.game_dir)
        except ValueError:
            return "cd \\"
        relative_text = str(relative).replace("/", "\\")
        return f"cd \"\\{relative_text}\""

    def render_autoexec_text(self, profile: MachineProfile) -> str:
        if profile.autoexec_text.strip():
            return profile.autoexec_text.strip()
        return self.default_autoexec_text(profile.game, profile.engine.binary_path)

    def default_autoexec_text(self, game: GameTargets, engine_binary: Path | None = None) -> str:
        return "\n".join(self._default_autoexec_prefix(game, engine_binary))

    def _default_autoexec_prefix(self, game: GameTargets, engine_binary: Path | None) -> list[str]:
        if engine_binary is not None and detect_engine_family_from_name(engine_binary) == ENGINE_FAMILY_DOSBOX_X:
            return [
                "# Lines in this section are run at startup.",
                'mount c ".."',
                "c:",
                "cd .dosmachines",
                "cd ..",
            ]
        return [
            "# Lines in this section are run at startup.",
            f"mount c \"{game.game_dir}\"",
            "c:",
            self._render_cd_from_game(game),
        ]
