from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import shutil

from dos_machines.application.engine_registry import EngineRegistry
from dos_machines.application.profile_service import CreateProfileRequest, ProfileService
from dos_machines.domain.models import MachineProfile, OptionState


_SECTION_RE = re.compile(r"^\s*\[([^\]]+)\]\s*$")
_MANAGED_HEADER = "# Generated by DOS Machines"


@dataclass(slots=True)
class ImportAnalysis:
    config_path: Path
    is_managed_config: bool
    title: str
    game_dir: Path
    executable: str
    engine_binary: Path
    option_states: dict[str, dict[str, OptionState]]
    autoexec_text: str
    raw_overrides: dict[str, dict[str, str]]


class ImportService:
    def __init__(self, engine_registry: EngineRegistry, profile_service: ProfileService) -> None:
        self._engine_registry = engine_registry
        self._profile_service = profile_service

    def can_import(self, path: Path) -> bool:
        return path.name.lower() in {"dosbox.conf", "dosbox-x.conf"}

    def import_config(self, config_path: Path, workspace_dir: Path) -> MachineProfile:
        analysis = self.analyse_config(config_path)
        request = CreateProfileRequest(
            title=analysis.title,
            game_dir=analysis.game_dir,
            executable=analysis.executable,
            engine_binary=analysis.engine_binary,
            workspace_dir=workspace_dir,
            option_states=analysis.option_states,
            autoexec_text=analysis.autoexec_text,
            raw_overrides=analysis.raw_overrides,
            import_source_path=analysis.config_path,
        )
        return self._profile_service.create(request)

    def analyse_config(self, config_path: Path) -> ImportAnalysis:
        resolved = config_path.expanduser().resolve()
        if not resolved.exists():
            raise FileNotFoundError(f"Config file does not exist: {resolved}")
        if not self.can_import(resolved):
            raise ValueError(f"Unsupported config file: {resolved.name}")

        engine_binary = self._detect_engine_binary(resolved)
        cache = self._engine_registry.register(engine_binary)
        schema = self._engine_registry.load_schema(cache.ref.engine_id)

        text = resolved.read_text(encoding="utf-8")
        parsed_sections, autoexec_lines = self._parse_config_text(text)
        is_managed = self._is_managed_config(resolved, text, autoexec_lines)
        game_dir = self._infer_game_dir(resolved, is_managed)
        executable = self._detect_executable(autoexec_lines)
        title = game_dir.name or resolved.stem

        option_states: dict[str, dict[str, OptionState]] = {}
        raw_overrides: dict[str, dict[str, str]] = {}
        schema_sections = {section.name: section for section in schema.sections}
        for section in schema.sections:
            if section.name == "autoexec":
                continue
            imported_values = parsed_sections.get(section.name, {})
            option_states[section.name] = {}
            for option in section.options:
                if option.name in imported_values:
                    option_states[section.name][option.name] = OptionState(
                        value=imported_values[option.name],
                        checked=True,
                        origin="imported",
                    )
                else:
                    option_states[section.name][option.name] = OptionState(
                        value=option.default_value,
                        checked=False,
                        origin="default",
                    )

        for section_name, values in parsed_sections.items():
            if section_name == "autoexec":
                continue
            schema_section = schema_sections.get(section_name)
            if schema_section is None:
                raw_overrides[section_name] = dict(values)
                continue
            schema_option_names = {option.name for option in schema_section.options}
            extras = {key: value for key, value in values.items() if key not in schema_option_names}
            if extras:
                raw_overrides[section_name] = extras

        autoexec_text = "" if is_managed else "\n".join(autoexec_lines).strip()
        return ImportAnalysis(
            config_path=resolved,
            is_managed_config=is_managed,
            title=title,
            game_dir=game_dir,
            executable=executable,
            engine_binary=engine_binary,
            option_states=option_states,
            autoexec_text=autoexec_text,
            raw_overrides=raw_overrides,
        )

    def _detect_engine_binary(self, config_path: Path) -> Path:
        candidates = ["dosbox-x", "dosbox", "dosbox-staging"] if config_path.name.lower() == "dosbox-x.conf" else [
            "dosbox",
            "dosbox-staging",
            "dosbox-x",
        ]
        for candidate in candidates:
            resolved = shutil.which(candidate)
            if resolved:
                return Path(resolved)
        raise FileNotFoundError("No DOSBox-family engine binary found in PATH.")

    def _parse_config_text(self, text: str) -> tuple[dict[str, dict[str, str]], list[str]]:
        sections: dict[str, dict[str, str]] = {}
        autoexec_lines: list[str] = []
        current_section: str | None = None

        for raw_line in text.splitlines():
            section_match = _SECTION_RE.match(raw_line)
            if section_match:
                current_section = section_match.group(1).strip().lower()
                if current_section != "autoexec":
                    sections.setdefault(current_section, {})
                continue
            if current_section == "autoexec":
                autoexec_lines.append(raw_line)
                continue
            if current_section is None:
                continue
            stripped = raw_line.strip()
            if not stripped or stripped.startswith(("#", ";")) or "=" not in raw_line:
                continue
            key, value = raw_line.split("=", 1)
            sections[current_section][key.strip().lower()] = value.strip()
        return sections, autoexec_lines

    def _is_managed_config(self, config_path: Path, text: str, autoexec_lines: list[str]) -> bool:
        if _MANAGED_HEADER in text:
            return True
        if config_path.parent.name == ".dosmachines":
            return True
        normalized = [line.strip().lower() for line in autoexec_lines if line.strip()]
        return any(".dosmachines" in line for line in normalized) and any(line == "cd .." for line in normalized)

    def _infer_game_dir(self, config_path: Path, is_managed: bool) -> Path:
        if is_managed and config_path.parent.name == ".dosmachines":
            return config_path.parent.parent
        return config_path.parent

    def _detect_executable(self, autoexec_lines: list[str]) -> str:
        ignored_prefixes = (
            "mount ",
            "imgmount ",
            "boot ",
            "config ",
            "keyb ",
            "echo ",
            "cls",
            "set ",
            "path ",
            "rem ",
            "::",
            "@echo",
            "cd ",
        )
        drive_pattern = re.compile(r"^[a-z]:\s*$", re.IGNORECASE)
        for raw_line in reversed(autoexec_lines):
            line = raw_line.strip()
            lowered = line.lower()
            if not line or lowered.startswith(("#", ";")):
                continue
            if drive_pattern.match(line):
                continue
            if lowered in {"exit"}:
                continue
            if lowered.startswith(ignored_prefixes):
                continue
            return line
        return ""
